//libs
const mechanics = require('../libs/mechanics/mechanics');

const {
    averageVelocity,
    averageAcceleration,
    velocity,
    displacement,
    netForce,
    weight,
    kineticFriction,
    centripetalAcceleration,
    momentum,
    impulse,
    impulseMomentum,
    work,
    workEnergy,
    kineticEnergy,
    gravitationalPotentialEnergy,
    efficiency,
    averagePower,
    powerVelocity,
    averageAngularVelocity,
    averageAngularAcceleration,
    angularVelocity,
    torque,
    netTorque,
    momentOfInertia,
    rotationalWork,
    rotationalPower,
    rotationalKineticEnergy,
    angularMomentum,
    angularImpulse,
    angularImpulseMomentum,
    universalGravitation,
    gravitationalField,
    gravitationalPotentialEnergy2,
    gravitationalPotential,
    orbitalSpeed,
    escapeSpeed,
    hookesLaw,
    springPotentialEnergy,
    simpleHarmonicOscillator,
    simplePendulum,
    frequency,
    angularFrequency,
    density,
    pressure,
    pressureInAFluid,
    buoyancy,
    massFlowRate,
    volumeFlowRate,
    dynamicViscosity,
    kinematicViscosity,
    drag,
    machNumber,
    reynoldsNumber,
    froudeNumber,
    youngsModulus,
    shearModulus,
    bulkModulus,
    surfaceTension,
} = mechanics;

//Mechanics Tests
describe('Mechanics', () => {
   //
});